### PR TITLE
center PCB design files and hand rest stls

### PR DESCRIPTION
**Pull request by IronFox**
Made some further improvements to the PCB and hand rests. No guarantee either works for everyone but I think they pose useful additions

### CODE REVIEW

**Comment by JesusFreke** [comment]
Awesome, thanks for the contribution!

**Comment by JesusFreke** [comment]
btw, any chance you can share a more useful/modifiable form of the hand rest stls? e.g. if they were designed in openscad, then the .scad file, etc.

**Comment by IronFox** [comment]
> btw, any chance you can share a more useful/modifiable form of the hand rest stls? e.g. if they were designed in openscad, then the .scad file, etc.

Well, I'm kinda embarrassed to say I made these in 3ds Max. I can provide the .max files but I have this suspicion that other formats/programs would be more suitable. 3ds Max can do the required Boolean operations; it just isn't very good at it. Sometimes I had to switch the order of operands for it to not leave out big chunks of surface geometry.
The primary reason I didn't switch is because I know how to use 3ds Max and I wanted to focus on working, not learning. Kinda stupid, I know. Sort of a similar reason like why Minecraft runs on Java.
Anyway, I suspect 3ds Max is at least sufficiently high up when it comes to cage-based smooth modelling, which I used in this.
If you can translate the files, or think that .max is fine, too, I'll add the files.

**Comment by JesusFreke** [comment]
Ah, no worries, just using something that you're already familiar with is perfectly acceptable :)

I'm not familiar with 3ds Max, but that's better than just the .stl, imo :). I liken it a bit to the source code of a program, with the .stl file being the executable output. It's useful if you just want to use the model as-is, but it's not nearly as useful if you want to make changes to it.

If I get some time, I may try to translate the design to fscad -- but that will likely be much easier with the .max files available, rather than trying to reverse engineer the dimensions from the STLs :)

**Pull request merged**
